#!/usr/bin/env bash
# Builds a cross-compilation sysroot for the Miyoo Mini Plus (ARM Cortex-A7, Onion OS).
# Run once before building:  ./scripts/setup-sysroot.sh
#
# Why Docker: the device runs glibc 2.28. A modern distro's armhf toolchain
# (e.g. Ubuntu 24.04 "noble") links __libc_start_main@GLIBC_2.34 and
# __stat64_time64@GLIBC_2.34, and the resulting binary dies at exec with
#   "version `GLIBC_2.34' not found"
# before main() runs. The Onion toolchain image is glibc 2.28 and matches.
#
# The image's sysroot carries the SDL 1.2 stack (SDL 1.2.0.11.4, SDL_ttf
# 2.0.10.1, SDL_image 1.2.0.8.4 — the same builds shipped in the card's
# miyoo/lib) but it has NO json-c and NO libcurl (it ships cJSON instead), so
# those two come off the SD card itself, which guarantees an exact ABI match
# with what the app will link against at runtime.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SYSROOT="$ROOT/sysroot"
VENDOR="$ROOT/vendor"
IMAGE="${TOOLCHAIN_IMAGE:-ghcr.io/onionui/miyoomini-toolchain:latest}"

# Versions the device actually runs — read off the binaries with:
#   grep -a -oE 'libcurl/[0-9.]+' .tmp_update/lib/libcurl.so.4
#   readelf -V --wide App/pico/lib/libjson-c.so.5 | grep -oE 'JSONC_[0-9.]+'
JSONC_TAG="json-c-0.15-20200726"
CURL_VER="8.1.0"

say() { printf '\033[1m==\033[0m %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

command -v docker >/dev/null || die "docker is required (the cross-toolchain lives in $IMAGE)"
docker info >/dev/null 2>&1 || die "cannot talk to the docker daemon"

# ── Device libraries (cached in vendor/ after the first run) ─────────
DEVLIBS="$VENDOR/device-libs"
if [ ! -f "$DEVLIBS/libjson-c.so.5" ] || [ ! -f "$DEVLIBS/libcurl.so.4" ]; then
    say "Collecting json-c and libcurl from the SD card"

    if [ -z "${SDCARD:-}" ]; then
        for c in "/media/$USER/Onion" /mnt/SDCARD /Volumes/Onion; do
            [ -d "$c" ] && { SDCARD="$c"; break; }
        done
    fi
    [ -n "${SDCARD:-}" ] && [ -d "$SDCARD" ] || die \
"could not find a mounted Onion SD card.
       Mount the card and re-run, or point at it explicitly:
         SDCARD=/path/to/sdcard $0
       (only needed once — the libraries are cached in vendor/)"

    src_json="$SDCARD/App/pico/lib/libjson-c.so.5"   # shipped with the Pico-8 app
    src_curl="$SDCARD/.tmp_update/lib/libcurl.so.4"  # shipped with Onion itself
    [ -f "$src_json" ] || die "no libjson-c.so.5 at $src_json"
    [ -f "$src_curl" ] || die "no libcurl.so.4 at $src_curl"

    mkdir -p "$DEVLIBS"
    cp "$src_json" "$src_curl" "$DEVLIBS/"
    echo "   from $SDCARD"
else
    say "Using cached device libraries in vendor/device-libs"
fi

# ── Matching headers (fetched on the host: the image has no curl/wget) ──
INC="$VENDOR/include"
fetch() {
    if command -v curl >/dev/null; then curl -sfL -o "$1" "$2"
    elif command -v wget >/dev/null; then wget -qO "$1" "$2"
    else die "need curl or wget on the host to download headers"; fi
}

if [ ! -f "$INC/json-c/json.h" ] || [ ! -f "$INC/curl/curl.h" ]; then
    say "Downloading json-c and curl headers"
    tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT

    fetch "$tmp/jsonc.tar.gz" \
        "https://github.com/json-c/json-c/archive/refs/tags/${JSONC_TAG}.tar.gz"
    tar -xzf "$tmp/jsonc.tar.gz" -C "$tmp"
    mkdir -p "$INC/json-c"
    cp "$tmp/json-c-${JSONC_TAG}"/*.h "$INC/json-c/"

    # json_config.h is generated by json-c's build system; the release tarball
    # ships only the .in template, so provide the ARM Linux answer directly.
    cat > "$INC/json-c/json_config.h" <<'EOF'
/* Minimal json_config.h for cross-compiling against json-c 0.15 (ARM Linux). */
#ifndef JSON_C_CONFIG_H
#define JSON_C_CONFIG_H
#define JSON_C_HAVE_INTTYPES_H 1
#endif
EOF

    fetch "$tmp/curl.tar.gz" "https://curl.se/download/curl-${CURL_VER}.tar.gz"
    tar -xzf "$tmp/curl.tar.gz" -C "$tmp"
    mkdir -p "$INC/curl"
    cp "$tmp/curl-${CURL_VER}/include/curl"/*.h "$INC/curl/"
else
    say "Using cached headers in vendor/include"
fi

# ── Assemble the sysroot inside the toolchain container ─────────────
say "Pulling $IMAGE (first run only, ~3 GB)"
docker image inspect "$IMAGE" >/dev/null 2>&1 || docker pull "$IMAGE"

say "Assembling sysroot"
docker run --rm -v "$ROOT":/work "$IMAGE" bash -euo pipefail -c '
IMG_SR=/opt/miyoomini-toolchain/usr/arm-linux-gnueabihf/sysroot
SR=/work/sysroot
TRIPLET=arm-linux-gnueabihf

rm -rf "$SR"; mkdir -p "$SR"
cp -a "$IMG_SR"/. "$SR"/

# The Makefile looks in usr/lib/<triplet>; this toolchain keeps libs flat in
# usr/lib, so mirror them across as symlinks.
mkdir -p "$SR/usr/lib/$TRIPLET"
for f in "$SR"/usr/lib/*.so* "$SR"/usr/lib/*.a; do
    [ -e "$f" ] || continue
    ln -sf "../$(basename "$f")" "$SR/usr/lib/$TRIPLET/$(basename "$f")"
done

# The device s own json-c 0.15 and libcurl 8.1.0
cp /work/vendor/device-libs/libjson-c.so.5 "$SR/usr/lib/"
cp /work/vendor/device-libs/libcurl.so.4   "$SR/usr/lib/"
ln -sf libjson-c.so.5 "$SR/usr/lib/libjson-c.so"
ln -sf libcurl.so.4   "$SR/usr/lib/libcurl.so"
for l in libjson-c.so.5 libjson-c.so libcurl.so.4 libcurl.so; do
    ln -sf "../$l" "$SR/usr/lib/$TRIPLET/$l"
done

mkdir -p "$SR/usr/include/json-c" "$SR/usr/include/curl"
cp /work/vendor/include/json-c/*.h "$SR/usr/include/json-c/"
cp /work/vendor/include/curl/*.h   "$SR/usr/include/curl/"
'

say "Sysroot ready at $SYSROOT"
echo "   Build with: ./scripts/build.sh"
